### PR TITLE
prepare.py: single-threaded write with mmap only once

### PR DESCRIPTION
**Pull request by proger**
Thanks for publishing nanoGPT! I've been learning a lot by reading your code.

When preparing a 5.4G (binary) corpus with 16 threads, `prepare.py` crashed with OOM after consuming all of my 90G of RAM.

I've reduced concurrency of writes to 1, assuming the disks probably aren't _that_ fast.

Next, I've noticed a very large estimate to completion and saw that opening and mmapping and flushing the output on every example incurs a large overhead. Running `mmap` beforehand and flushing only once at the end gives a 22x speedup, currently writing at 29.5 ex/s.

image

### CODE REVIEW

**Comment by karpathy** [comment]
Ouch, thank you for reporting. I didn't notice this because my dev box is too beefy.  Have you tried using fewer than 16 workers, e.g. 4, with the original implementation? I'm a bit uncertain about this new way, with 1 worker does it essentially become a serial for loop?

**Comment by proger** [comment]
Yeah, I was counting on it to become a serial for loop because I am unsure about possible interactions between `.map` and `mmap`. 

I'm going to try the original setup with less workers and 16 workers with a shared mmap file (which I hope in theory is also fine) once my current write completes.

**Comment by LaihoE** [comment]
This gives me identical output to the original. Original took me around 3h and this ~30min. Didn't have any problems with RAM during both.
```python
# concatenate all the ids in each dataset into one large file we can use for training
for split, dset in tokenized.items():
    arr_len = np.sum(dset['len'])
    filename = f'{split}.bin'
    dtype = np.uint16 # (can do since enc.max_token_value == 50256 is < 2**16)
    arr = np.memmap(filename, dtype=dtype, mode='w+', shape=(arr_len,))
    
    idx = 0
    for example in tqdm(dset):
        arr[idx : idx + example['len']] = example['ids']
        idx += example['len']
    arr.flush()
```

**Comment by karpathy** [comment]
@LaihoE ok so this is also a pure vanilla for loop. I was trying to write the code so it is scalable to much larger datasets (e.g. I'd like to eventually train on Pile and beyond). It could be that the default of 16 is not good. @LaihoE did you try with smaller worker sizes? I'm currently working on something else but can join the debugging efforts later in the afternoon.

**Comment by LaihoE** [comment]
Tried with 1 and 4 processes with no luck. Both seemed to take around 4-5h. I also tried with shared memory (similarly to what the flashattention repo did) but that didn't help much.

I think the problem is that you are doing more or less random writes. Would need to batch together ids and write in one go.

**Comment by proger** [comment]
> Have you tried using fewer than 16 workers, e.g. 4, with the original implementation? 

I am getting OOMs in all cases where I'm using multiprocessing with `map`. I also tried to use `batch=True` to open the file once per batch and got OOMs. My iteration speed is limited by slow loading of the tokenized data from HF datasets cache. When I `py-spy dump` the script it seems to be writing something. 

I like @LaihoE's loop. It could scale if the parallelisation happens, say, on the level of each split of The Pile.

**Comment by karpathy** [comment]
Adopted @LaihoE suggestion in https://github.com/karpathy/nanoGPT/commit/7c6ea8409e44deb188b4c3213c01fd1e9174537a for now, ty all. Will close this PR shortly.

**Comment by hwijeen** [comment]
Could someone explain why we want to use `np.memmap` instead of using datasets' `save_to_disk` function? I thought mmap was used anyways under the hood and curious what could be the additional benefit of doing this manually. Thanks in advance!

**Pull request closed without merging**
