### PR TITLE
Don't hard-code device in autocast

### PR DESCRIPTION
**Pull request by lantiga**
Another nano PR 😁
Code is device-independent except for the argument of the autocast context, this PR fixes it.
With this change you can dry-run train.py on a laptop.

### CODE REVIEW

**Comment by karpathy** [comment]
Interesting I wasn't aware you can just pass the device directly into device_type, the docs make it sound like:

```
device_type ([str](https://docs.python.org/3/library/stdtypes.html#str), required) – Whether to use ‘cuda’ or ‘cpu’ device
```

it would be either 'cuda' or 'cpu', strictly. Are we sure this works e.g. when cuda:0, or in the near future mps, or something like that? Also should potentially change the sample.py, bench.py, etc?

**Comment by lantiga** [comment]
Whoops, my bad, you're totally right, let me fix the PR in that sense.

**Comment by lantiga** [comment]
At this point let's skip autocast altogether for unsupported autocast devices (e.g. mps), I hope it doesn't make the code too complex.

**Comment by karpathy** [comment]
not good, there must be a better way. was earlier thinking of an `if else then` one-liner to set the context. set to nullcontext if want to skip, see
https://stackoverflow.com/questions/45187286/how-do-i-write-a-null-no-op-contextmanager-in-python

maybe something like that?

**Comment by karpathy** [comment]
`device_type = 'cuda' if 'cuda' in device else 'cpu'`
I don't like to create blocks of code as a general rule

**Comment by karpathy** [comment]
I think hold off on this PR, it is entangled with some future plans I have for how to handle/override the `device` too. Thank you though!

**Comment by lantiga** [comment]
Sounds good! Totally second the willingness to keep it as plain as possible

**Comment by lantiga** [comment]
BTW thanks for the pointer to nullcontext though, I wasn't aware :-)

**Comment by karpathy** [comment]
Great! I just pushed the changes btw, ty!

**Comment by lantiga** [comment]
Awesome, looks nice and clean

**Comment by Majdoddin** [comment]
@karpathy @lantiga 
why still no autocast for CPU? For example, change 
https://github.com/karpathy/nanoGPT/blob/a82b33b525ca9855d705656387698e13eb8e8d4b/sample.py#L32
to
```
ctx =  nullcontext() if device_type == 'cpu' and dtype != 'bfloat16' else torch.amp.autocast(device_type=device_type, dtype=ptdtype) #CPU Autocast only supports dtype of torch.bfloat16 currently.
```
besides, does it make sense to use IPEX ([intel extension for pytorch](intel_extension_for_pytorch ))? [Here ](https://huggingface.co/docs/transformers/v4.24.0/en/perf_train_cpu) it says it boosts performance.

**Pull request closed without merging**
