### PR TITLE
[easy] allow multithreading in load_dataset

### PR DESCRIPTION
**Pull request by okuvshynov**
Both loading from the network and generating train split can benefit from multithreading (especially on larger instances/faster network). 

On 30 CPU + single A100 lambda instance it brings down the time to get the data from ~35min (28 threads for tokenizing, 1 thread for load_dataset) to ~8min (28 threads for both).

CPU util looks like this:

28 thread load_dataset (finished): 
nanogpt_dataload_mt

1 thread load_dataset (still running):
nanogpt_dataload_1T

### CODE REVIEW

**Comment by karpathy** [comment]
doh I didn't know about this, thank you!!

**Comment by okuvshynov** [comment]
looks like we might have to revert this :( while it works well on Linux machines i tried it on, when I tried to download the data on Macbook it hangs somewhere in the library (unless I set num_proc=1)

**Comment by okuvshynov** [comment]
another option is to make ```num_proc_load_dataset=1``` , so that it works by default, but mention somewhere that we can set this higher.

**Comment by okuvshynov** [comment]
hopefully no need to revert.

https://github.com/karpathy/nanoGPT/commit/542ac51d1f98557f3c19bbea7047ed4add9c09d9 -- the issue was supposedly that multiprocessing module implementation on that platform cannot find entry point unless you define '__main__'. I'll test it and create new PR

**Pull request merged**
