### PR TITLE
cpu support

### PR DESCRIPTION
**Pull request by Ricardicus**
First of all, tank you Andrej Karpathy for the amazing Youtube series you have done on deep learning and for being such a great educator on the subject online.

Regarding this PR. I noticed that there was support for the poor mans configurator as well as data loader but I failed to find support for the poor mans hardware. I therefore added it. It might also be useful in case high performance, or performance in general, isn't a requirement or one would like to use the computer as some sort of electric heating system.

```
# in case there is no GPU but a lot of time to spend
python train.py finetune_shakespeare --device=cpu --init_from=gpt2
```

### CODE REVIEW

**Comment by karpathy** [comment]
haha good idea actually thanks. Should we detect device type based on device though? Leaning to yes

**Comment by Ricardicus** [comment]
Leaning towards a yes on that one... will fix comment above so it shows how it is done

**Comment by lzeladam** [comment]
Hi @Ricardicus ,

Thank you for updating the code, but I tested it in my local environment with --device=cpu and encountered an error stating that the AutocastCPU feature only supports bfloat16 data types.

`RuntimeError: Currently, AutocastCPU only supports Bfloat16 as the autocast_cpu_dtype`

some suggestions?

**Comment by Ricardicus** [comment]
Hi @lzeladam ,

First of all, don't use the cpu if you have a gpu hehe ;)
But I don't have this issue, since I use bfloat16 on my CPU. Have you changed the dtype perhaps?

Both line 196 and 256 look like this:
```
with torch.amp.autocast(device_type=device_type, dtype=torch.bfloat16):
```

**Comment by Ricardicus** [comment]
I have updated so that if device type is set to cpu when device is set to cpu. There is only cpu and cuda as device types in PyTorch as it stands today right?

**Comment by Ricardicus** [comment]
Moved the device type from the configurator area, so that it is only set based on device. Made more sense

**Comment by karpathy** [comment]
I think this is part of a bigger refactor I'd like to make because I want both device and dtype to be configurable from args. And potentially apply the autocast context manager only where it makes sense (e.g. 'cuda' and 'bfloat16'). And 'float16' is currently not super supported because there is no gradient scaler...

**Comment by Ricardicus** [comment]
Ok, I can see how this opens up the door to future configurations and modalities. As its stands today I thought it would be nice with some cpu empowering. The 'cpu' and 'bfloat16' case also makes sense. I think Izeladam above used 'cpu' and 'float16' which caused problems. How would one set the dtype from aguments? I can see how it is set from a configuration file, but "literal_eval" would not accept "torch.bfloat16" as an expression. Maybe some string inspection from args would be necessary there. I'd still use the current configurator over argparse or something like that. I think the crossing of fingers part of PMC (Poor Mans Configurator) is a bit charming/entertaining and replacing PMC would be out of scope for what I was trying to achieve here.

Would it be helpful if I made dtype configurable somehow from args in this PR as well? I think you'd do a better job of implementing the decision process for when to and when not to apply the autocast context manager, and I propably would leave that out of scope of this PR as well...

**Comment by karpathy** [comment]
CPU support is now added so closing this issue ty

**Comment by MurageKibicho** [comment]
@Ricardicus I've been using your LSTM implementation. Would you want to collaborate and write a C version of nanoGPT. I think it would be a great addition to your AI portfolio. 

P.S I was browsing through nanoGPT's issue history and I recognized your username. Amazing work!

**Pull request closed without merging**
