### PR TITLE
Zero-grad more aggressively to save memory

### PR DESCRIPTION
**Pull request by cchan**
Same as https://github.com/karpathy/minGPT/pull/106 - sorry for the spam, am actually using both of these repos (they've been insanely useful <3)

### CODE REVIEW

**Comment by karpathy** [comment]
@cchan can you share intuition on why this makes so much difference?

**Comment by cchan** [comment]
@karpathy it's just that after you run `backward()` and before you run `zero_grad(set_to_none=True)`, your gradient tensors are actually still taking up space in memory. Importantly, your gradients are still around *at the moment you've finished the forward pass*, which is the most memory intensive because of all the activations that need to be kept around for gradient calculations later.

Here's a bad diagram to mull over :) this is actually almost exactly what the real memory profile for minGPT looks like.

Screen Shot 2023-01-20 at 2 02 51 PM

As a side note, if you think about it you can also eliminate the purple memory almost entirely if you run the optimizer immediately once you generate the gradient tensor. But that doesn't improve peak memory usage, which is what matters.

**Comment by karpathy** [comment]
I'm not sure if I follow because my original code zero_grads right before the forward pass, so those gradients should be gone during the forward pass.

**Comment by cchan** [comment]
Ah for nanoGPT you might be right. In minGPT it's [right after the fwd](https://github.com/karpathy/minGPT/pull/106/files#diff-7e7c872a22f4807ecaf356a3b4a3a8086c085308474d68a52672feb61ed3c1cdL93) but not here.

My habit is just to zero_grad(set_to_none=True) immediately after the optimizer, since you might as well get rid of gradients ASAP.

**Comment by karpathy** [comment]
ok that makes more sense :) yes I agree with you, feels much better and safer to free it right away once it is not needed.

**Comment by vgoklani** [comment]
Hey @cchan where did you get that diagram from? Could you please share the URL. thanks!

**Comment by cchan** [comment]
@vgoklani I drew it on an MS Paint-like website in about 10 minutes lol, why?

**Comment by vgoklani** [comment]
@cchan it's a pretty professional-looking drawing! 

I was looking for some info about optimizing memory usage during training...

**Pull request merged**
