### PR TITLE
Argparse but vars remain at global level and minimal boilerplate

### PR DESCRIPTION
**Pull request by murbard**
Probably a terrible idea, but still a Pareto improvement.

### CODE REVIEW

**Comment by karpathy** [comment]
so I tried something like this but my VS Code editor started to underline every single variable with yellow because it thought it was undefined. This would still have the same behavior by default right?

**Comment by murbard** [comment]
Yes, the downside is that the editor doesn't know those variables are initialized. An alternative is to move much of the code of train inside a function, and decorate the function to automatically generate a parse.

```python
from configurator import argparser

@argparser
def train(
    out_dir : str = 'out',
    eval_interval : int = 2000,
    log_interval : int = 1,
    eval_iters : int = 200,
    eval_only : bool = False,
    always_save_checkpoint : bool = True,
    init_from : str = 'scratch',
    wandb_log : bool = False,
    wandb_project : str = 'owt',
    wandb_run_name : str = 'gpt2',
    dataset : str = 'openwebtext',
    batch_size : int = 12,
    block_size : int = 1024,
    n_layer : int = 12,
    n_head : int = 12,
    n_embd : int = 768,
    dropout : float = 0.0,
    learning_rate : float = 6e-4,
    max_iters : int = 600000,
    weight_decay : float = 1e-2,
    betas : tuple = (0.9, 0.95),
    decay_lr : bool = True,
    warmup_iters : int = 2000,
    lr_decay_iters : int = 600000,
    min_lr : float = 6e-5,
    backend : str = 'nccl',
    device : str = 'cuda',
    compile : bool = True,
    config_file : str = None):
    """
    Train a GPT-2 model on a dataset.
    :param str out_dir: output directory
    :param int eval_interval: number of iterations between evaluations
    :param int log_interval: number of iterations between logging
    :param int eval_iters: number of iterations to run evaluation for
    :param bool eval_only: if True, script exits right after the first eval
    :param bool always_save_checkpoint: if True, always save a checkpoint after each eval
    :param str init_from: scratch, resume, or gpt2*
    :param bool wandb_log: whether to log to wandb
    :param str wandb_project: wandb project name
    :param str wandb_run_name: wandb run name
    :param str dataset: dataset name
    :param int batch_size: batch size
    :param int block_size: block size
    :param int n_layer: number of layers
    :param int n_head: number of heads
    :param int n_embd: embedding dimension
    :param float dropout: dropout rate
    :param float learning_rate: max learning rate
    :param int max_iters: total number of training iterations
    :param float weight_decay: weight decay
    :param tuple betas: betas
    :param bool decay_lr: whether to decay the learning rate
    :param int warmup_iters: how many steps to warm up for
    :param int lr_decay_iters: should be ~= max_iters per Chinchilla
    :param float min_lr: minimum learning rate, should be ~= learning_rate/10 per Chinchilla
    :param str backend: nccl, gloo, etc.
    :param str device: device
    :param bool compile: use PyTorch 2.0 to compile the model to be faster
    """
    ```
    
    and 
    
    ```python
    import inspect
import argparse

def argparser(func):
    # Get the function's parameter names and default values
    params = inspect.signature(func).parameters
    param_defaults = {name: param.default for name, param in params.items()}
    param_types = {name: param.annotation for name, param in params.items()}

    # Create the ArgumentParser
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    docstring = func.__doc__ or ''
    param_lines = [line for line in [line.strip() for line in docstring.split('\n')] if  line.startswith(':param')]
    param_info = {}
    for line in param_lines:
        param, description = line.split(':', 1)[1].strip().split(':', 1)
        param = param[6:]
        print(param, "####", description)
        if ' ' in param:
            param_type, param_name  = param.split(' ', 1)
            param_type = param_type.strip()
        else:
            param_name = param.strip()
            param_type = None
        param_info[param_name] = (param_type, description.strip())
    print(param_info)

    # Add an argument for each parameter
    for name, default in param_defaults.items():
        # Use the parameter's type annotation if it's present,
        # otherwise use the type of the default value or the type type
        param_type = param_types[name]
        if param_type is inspect.Parameter.empty:
            param_type = type(default)
        # Determine whether the argument is required
        required = default is inspect.Parameter.empty
        description = param_info.get(name, (None, None))[1]
        parser.add_argument(f'--{name}', default=default, type=param_type, required=required, help=description)

      # Define a wrapper function that parses the command-line arguments and calls the original function
    def wrapper(*args, **kwargs):
        # Parse the command-line arguments
        kwargs = vars(parser.parse_args())

        # Call the original function with the updated keyword arguments
        return func(**kwargs)

    return wrapper
    ```

**Comment by karpathy** [comment]
actually I don't hate the idea of using a function def. Is this much better than the Poor Man's Configurator though? be honest

**Comment by murbard** [comment]
It's useful to be able to type 'python train.py -h' and get the documentation for the various configurations, and it's nice to avoid global variables

A third option is to keep the global variable assignments as is, but inspect the source code at runtime, and generate the correct argparser object based on the variable name, default value, and comment.

**Comment by karpathy** [comment]
I am going to keep code as is here because I don't think the added complexity is currently worth the benefits. There is no need for a -h view of args when they are simply listed out in a single block up top on the script. If the code later complexifies to the point that the args not as easily inspectable I will be more inclined to seek a solution to that problem. Ty for the suggestions though!

**Pull request closed without merging**
