### PR TITLE
add template .gitattributes that fixes language stats

### PR DESCRIPTION
**Pull request by akashmjn**
Tiny PR to fix the annoying jupyter notebook language count stats :) 

https://twitter.com/karpathy/status/1620875263700799488?s=20&t=bV2NXNJaUzxcZWsUyDyJEg

Instructions taken from https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code, referenced in discussion under https://github.com/github/linguist/issues/3316 (official github-linguist repo). 

I left the rest of the commented template lines in there in case you need anything from there, but could remove them if you really want to keep it "nano" 😉

### CODE REVIEW

**Comment by karpathy** [comment]
why is this file so long? does it need to be just that 1 line with a comment?

**Comment by akashmjn** [comment]
Correct, you only really need [lines 6-8](https://github.com/akashmjn/nanoGPT/blob/0e2c12b5ae633cda29a41f66ecc6cd6ed3d6b50e/.gitattributes#L6-L8) 

Initially lazily copied a template i'd used elsewhere in case something else may be of use (just looked, it isn't). Fixing in follow up.

**Comment by karpathy** [comment]
cool, let's see what happens :) ty!

**Comment by karpathy** [comment]
i think it worked, ty :) 
image

**Comment by akashmjn** [comment]
Nice! 🥳

**Pull request merged**
